[package]
name = "rt-rs"
version = "0.1.0"
authors = ["zehreken <zehreken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
rand = "0.8.4"
minifb = "0.20.0"
puffin = "0.12.1"

[dependencies.sdl2]
version = "0.35.1"
default-features = false
