pub mod camera;
pub mod core;
pub mod cube;
pub mod light;
pub mod material;
pub mod primitive;
pub mod quad;
// pub mod scene;
// pub mod scene2;
pub mod scene;
pub mod scene_constructor;
pub mod shader_data;
// pub mod sphere;
// pub mod triangle;
pub mod uniforms;
